In [1]:
import numpy as np

In [9]:
haystack = [1, -1, 1, 1, 1, -1, 1, 1, 1]
needle = np.array([1, -1, 1, 1, -1, 1])

In [10]:
nsamp = len(needle)
nsamp

6

In [11]:
def compare(needle, haystack):
    nsamp = len(needle)
    for pos in range(len(haystack) - nsamp + 1):
        comp = np.array(haystack[pos:pos + nsamp])
        score = np.dot(needle, comp)
        print(f'\nPosition {pos}:\n  {comp}\n  {needle} score: {score}')

In [12]:
compare(needle, haystack)


Position 0:
  [ 1 -1  1  1  1 -1]
  [ 1 -1  1  1 -1  1] score: 2

Position 1:
  [-1  1  1  1 -1  1]
  [ 1 -1  1  1 -1  1] score: 2

Position 2:
  [ 1  1  1 -1  1  1]
  [ 1 -1  1  1 -1  1] score: 0

Position 3:
  [ 1  1 -1  1  1  1]
  [ 1 -1  1  1 -1  1] score: 0


In [13]:
haystack = [1, 2, 3, 4, 5, 6]
needle = np.array([1, 2, 3])
compare(needle, haystack)


Position 0:
  [1 2 3]
  [1 2 3] score: 14

Position 1:
  [2 3 4]
  [1 2 3] score: 20

Position 2:
  [3 4 5]
  [1 2 3] score: 26

Position 3:
  [4 5 6]
  [1 2 3] score: 32
